#!/usr/bin/env bash

# ./compile coursework msString
if (($# == 0)); then
  gcc -ansi -c msString.c -o msString.o
  gcc -ansi -c coursework.c -o coursework.o
  gcc -ansi -o coursework msString.o coursework.o
else 
  gcc -ansi -c ${2}.c -o ${2}.o
  gcc -ansi -c ${1}.c -o ${1}.o
  gcc -ansi -o ${1} ${2}.o ${1}.o
fi

# For development I used somthing like this:
# 
# function compile () {
  # if (($# == 1)); then
    # if [[ "${1}" != *.c ]] && [[ "${1}" != *.o ]]; then
      # gcc -ansi -c ${1}.c -o ${1}.o
      # gcc ${1}.o -o ${1}
    # else 
      # echo "You left the .c on again"
      # gcc -ansi -c ${1:0:-2}.c -o ${1:0:-2}.o
      # gcc ${1:0:-2}.o -o ${1:0:-2}
    # fi
  # else
    # gcc -ansi -c ${2}.c -o ${2}.o
    # gcc -ansi -c ${1}.c -o ${1}.o
    # gcc -ansi -o ${1} ${2}.o ${1}.o
  # fi
# }
#
# I kept using autocomplete, which added the .c/.
